services:
  - type: web
    name: credit-scoring-api
    runtime: python
    plan: free  # Use 'starter' for production
    branch: main
    buildCommand: pip install --upgrade pip==23.3.1 && pip install --no-compile --only-binary=all -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: PYTHONPATH
        value: /opt/render/project/src
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: render-disk
      mountPath: /opt/render/project/src
      sizeGB: 1
